name: Node.js CI

on:
  push:
    branches:
      - develop # Adicione 'develop' para que o workflow dispare nessa branch
      - feature/* # Mantém a regra para branches de features

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22" # Ou outra versão que você use

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
  merge:
    runs-on: ubuntu-latest
    needs: test
    if: success()

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set Git user
        run: |
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"

      - name: Create main branch if it doesn't exist
        run: |
          git checkout -b main || git checkout main

      - name: Merge branch
        run: |
          git merge --no-ff ${{ github.ref }}
          git push origin main
